development:
  adapter: postgresql
  database: ganas_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ganas_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ganas_production
  pool: 5
  timeout: 5000
